# Generated by Django 5.0.3 on 2024-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_ride_created_at_remove_ride_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
